# coding: utf-8

"""
    Blockout Pools Service Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict
from typing_extensions import Annotated
from blockout_contract_clients.pools_service.models.format_enum import FormatEnum
from blockout_contract_clients.pools_service.models.gender_enum import GenderEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PoolInternalResponse(BaseModel):
    """
    Pool owner projection without persistence audit timestamps or BFF-derived division, ranking, match, and team data.
    """ # noqa: E501
    id: Annotated[int, Field(strict=True, ge=1)]
    pool_code: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="poolCode")
    league_code: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="leagueCode")
    season: Annotated[str, Field(strict=True, max_length=255)]
    league_name: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="leagueName")
    raw_name: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="rawName")
    name: Annotated[str, Field(strict=True, max_length=255)]
    short_name: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="shortName")
    division_id: Annotated[int, Field(strict=True, ge=1)] = Field(alias="divisionId")
    format: FormatEnum
    gender: GenderEnum
    followers_count: Annotated[int, Field(strict=True, ge=0)] = Field(alias="followersCount")
    active: StrictBool
    __properties: ClassVar[List[str]] = ["id", "poolCode", "leagueCode", "season", "leagueName", "rawName", "name", "shortName", "divisionId", "format", "gender", "followersCount", "active"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PoolInternalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PoolInternalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "poolCode": obj.get("poolCode"),
            "leagueCode": obj.get("leagueCode"),
            "season": obj.get("season"),
            "leagueName": obj.get("leagueName"),
            "rawName": obj.get("rawName"),
            "name": obj.get("name"),
            "shortName": obj.get("shortName"),
            "divisionId": obj.get("divisionId"),
            "format": obj.get("format"),
            "gender": obj.get("gender"),
            "followersCount": obj.get("followersCount"),
            "active": obj.get("active")
        })
        return _obj
