services:
  blockout-api-reports:
    build: .
    ports:
      - ${SERVER_PORT}:8091
    environment:
      AUTH0_ISSUER: ${AUTH0_ISSUER}
    depends_on:
      postgres:
        condition: service_healthy