services:
  blockout-api-users:
    build: .
    ports:
      - ${SERVER_PORT}:8085
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_AUTH0_ISSUER: ${SPRING_AUTH0_ISSUER}
      SPRING_AUTH0_AUDIENCE: ${SPRING_AUTH0_AUDIENCE}
      SPRING_AUTH0_DOMAIN: ${SPRING_AUTH0_DOMAIN}
      SPRING_AUTH0_CLIENT_ID: ${SPRING_AUTH0_CLIENT_ID}
      SPRING_AUTH0_CLIENT_SECRET: ${SPRING_AUTH0_CLIENT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_NAME}
    ports:
      - 5436:5432
    volumes:
      - ./local/postgres-data:/var/lib/postgresql/data
      - ./local/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5