CREATE TABLE users
(
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth0_id     VARCHAR(255) NOT NULL,
  email        VARCHAR(255) NOT NULL,
  first_name   VARCHAR(255),
  last_name    VARCHAR(255),
  pseudo       VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255),
  picture_url  VARCHAR(255),
  active       BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMP(6),
  last_update  TIMESTAMP(6),
  CONSTRAINT uix_user_auth0_id UNIQUE (auth0_id),
  CONSTRAINT uix_user_email UNIQUE (email),
  CONSTRAINT uix_user_pseudo UNIQUE (pseudo)
);
