server:
  port: 8088

spring:
  application:
    name: ${APPLICATION_NAME:search}

  jackson:
    property-naming-strategy: SNAKE_CASE

  config:
    import: optional:file:.env.local[.properties]
    on-missing-location: fail

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    audience: ${AUTH0_AUDIENCE}