server:
  port: 8081 

spring:
  application:
    name: pools
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/blockout_pools
    username: blockout_pools
    password: blockout_pools
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: false  
    database-platform: org.hibernate.dialect.PostgreSQLDialect 

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password