server:
  port: 8082
  
spring:
  application:
    name: users

okta:
  oauth2:
    issuer: https://dev-jb2dhm4ou4owlr6e.eu.auth0.com/
    audience: https://blockoutapi/

auth0:
  domain: https://dev-jb2dhm4ou4owlr6e.eu.auth0.com
  client-id: kJBknZA41Iyot08oYgJwuJqpM7fwj02d
  client-secret: WVX6xfrfQpdF8-0aSrwLmDgXg5OHaIzIPqbca14x5PffK_uW6Mi2HniY3FbOrMc8

logging:
  level:
    org:
      springframework:
        security: DEBUG