CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id VARCHAR(255) NOT NULL,
    division_id BIGINT NOT NULL,
    format VARCHAR(255) NOT NULL CHECK (format IN ('SIX', 'FOUR')),
    gender VARCHAR(255) NOT NULL CHECK (gender IN ('M', 'F', 'O')),
    league_code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(255) NOT NULL,
    season VARCHAR(255) NOT NULL,
    followers_count BIGINT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6),
    last_update TIMESTAMP(6),
    CONSTRAINT uix_team UNIQUE (
        club_id,
        division_id,
        format,
        gender,
        name,
        season
    )
);