CREATE TABLE pools
(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pool_code       VARCHAR(255) NOT NULL,
  league_code     VARCHAR(255) NOT NULL,
  season          VARCHAR(255) NOT NULL,
  league_name     VARCHAR(255),
  name            VARCHAR(255),
  division_id     BIGINT       NOT NULL,
  format          VARCHAR(255) CHECK (format IN ('SIX', 'FOUR')),
  gender          VARCHAR(255) CHECK (gender IN ('M', 'F', 'O')),
  followers_count BIGINT       NOT NULL DEFAULT 0,
  active          BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMP(6),
  last_update     TIMESTAMP(6),
  CONSTRAINT uix_pool UNIQUE (pool_code, league_code, season)
);
