CREATE TABLE notification_send
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT      NOT NULL,
  match_id       BIGINT      NOT NULL,
  status         VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  expo_ticket_id VARCHAR(255),
  error_code     VARCHAR(64),
  error_detail   TEXT,
  sent_at        TIMESTAMP(6),
  delivered_at   TIMESTAMP(6),
  failed_at      TIMESTAMP(6),
  created_at     TIMESTAMP(6),
  last_update    TIMESTAMP(6),
  CONSTRAINT chk_notification_send_status CHECK (status IN ('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'SENT_NO_TOKEN')),
  CONSTRAINT uix_notification_send_user_match UNIQUE (user_id, match_id)
);

CREATE INDEX idx_notification_send_match ON notification_send (match_id);
CREATE INDEX idx_notification_send_status ON notification_send (status);
CREATE INDEX idx_notification_send_user ON notification_send (user_id);
