services:
  blockout-rabbitmq:
    container_name: blockout-rabbitmq
    image: rabbitmq:4-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: blockout
      RABBITMQ_DEFAULT_PASS: change-me
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - blockout-network

  blockout-pgadmin:
    container_name: blockout-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blockout.local
      PGADMIN_DEFAULT_PASSWORD: change-me
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - blockout-network

  blockout-elasticsearch:
    container_name: blockout-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - blockout-network

volumes:
  rabbitmq_data:
    name: blockout_rabbitmq_data
  pgadmin_data:
    name: blockout_pgadmin_data
  elasticsearch_data:
    name: blockout_elasticsearch_data
networks:
  blockout-network:
    name: blockout-network
