# coding: utf-8

"""
    Blockout Config Service Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GenderEnum(str, Enum):
    """
    Gender category used by Blockout competition data.
    """

    """
    allowed enum values
    """
    M = 'M'
    F = 'F'
    O = 'O'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GenderEnum from a JSON string"""
        return cls(json.loads(json_str))
