# coding: utf-8

"""
    Blockout Config Service Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateAppStatusInternalRequest(BaseModel):
    """
    Partial app-status update. Omitted and explicit-null fields both preserve the current stored value for compatibility.
    """ # noqa: E501
    maintenance: Optional[StrictBool] = None
    message: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    image_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, alias="imageUrl")
    min_version_ios: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, alias="minVersionIos")
    min_version_android: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, alias="minVersionAndroid")
    store_url_ios: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, alias="storeUrlIos")
    store_url_android: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, alias="storeUrlAndroid")
    force_update_message: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, alias="forceUpdateMessage")
    __properties: ClassVar[List[str]] = ["maintenance", "message", "imageUrl", "minVersionIos", "minVersionAndroid", "storeUrlIos", "storeUrlAndroid", "forceUpdateMessage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAppStatusInternalRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if maintenance (nullable) is None
        # and model_fields_set contains the field
        if self.maintenance is None and "maintenance" in self.model_fields_set:
            _dict['maintenance'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['imageUrl'] = None

        # set to None if min_version_ios (nullable) is None
        # and model_fields_set contains the field
        if self.min_version_ios is None and "min_version_ios" in self.model_fields_set:
            _dict['minVersionIos'] = None

        # set to None if min_version_android (nullable) is None
        # and model_fields_set contains the field
        if self.min_version_android is None and "min_version_android" in self.model_fields_set:
            _dict['minVersionAndroid'] = None

        # set to None if store_url_ios (nullable) is None
        # and model_fields_set contains the field
        if self.store_url_ios is None and "store_url_ios" in self.model_fields_set:
            _dict['storeUrlIos'] = None

        # set to None if store_url_android (nullable) is None
        # and model_fields_set contains the field
        if self.store_url_android is None and "store_url_android" in self.model_fields_set:
            _dict['storeUrlAndroid'] = None

        # set to None if force_update_message (nullable) is None
        # and model_fields_set contains the field
        if self.force_update_message is None and "force_update_message" in self.model_fields_set:
            _dict['forceUpdateMessage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAppStatusInternalRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "maintenance": obj.get("maintenance"),
            "message": obj.get("message"),
            "imageUrl": obj.get("imageUrl"),
            "minVersionIos": obj.get("minVersionIos"),
            "minVersionAndroid": obj.get("minVersionAndroid"),
            "storeUrlIos": obj.get("storeUrlIos"),
            "storeUrlAndroid": obj.get("storeUrlAndroid"),
            "forceUpdateMessage": obj.get("forceUpdateMessage")
        })
        return _obj
