export const CONFIG = {
    AUTH0_DOMAIN: process.env.EXPO_PUBLIC_AUTH0_DOMAIN || '',
    AUTH0_CLIENT_ID: process.env.EXPO_PUBLIC_AUTH0_CLIENT_ID || '',
    API_MATCHES_BASE_URL: process.env.EXPO_PUBLIC_API_MATCHES_BASE_URL || '',
    API_POOLS_BASE_URL: process.env.EXPO_PUBLIC_API_POOLS_BASE_URL || '',
    API_TEAMS_BASE_URL: process.env.EXPO_PUBLIC_API_TEAMS_BASE_URL || '',
    API_COMPETITIONS_BASE_URL: process.env.EXPO_PUBLIC_API_COMPETITIONS_BASE_URL || '',
};