# Configuration Nginx pour api.blockoutproject.com
user nginx;
worker_processes auto;

# Gestion des événements
events {
    worker_connections 1024;
}

# Configuration HTTP
http {
    include /etc/nginx/mime.types;   # Types MIME
    default_type application/octet-stream; # Type par défaut

    # Logs généraux
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Serveur HTTP pour les APIs
    server {
        listen 80;
        server_name api.blockoutproject.com;

        # API matches
        location /matches/v1 {
            proxy_pass http://host.docker.internal:8081; # Port du service matches
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API pools
        location /pools/v1 {
            proxy_pass http://host.docker.internal:8082; # Port du service pools
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API teams
        location /teams/v1 {
            proxy_pass http://host.docker.internal:8083; # Port du service teams
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Par défaut, bloquer tout le reste
        location / {
            return 404;
        }
    }
}