# coding: utf-8

"""
    Blockout Matches Service Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from blockout_contract_clients.matches_service.models.live_link_status_enum import LiveLinkStatusEnum
from blockout_contract_clients.matches_service.models.live_provider_enum import LiveProviderEnum
from blockout_contract_clients.matches_service.models.match_status_enum import MatchStatusEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MatchLiveModerationSummary(BaseModel):
    """
    Moderation projection using the audited representative-link priority. A status filter proves that some history row matches; the representative fields may describe a different status.
    """ # noqa: E501
    id: Annotated[int, Field(strict=True, ge=1)] = Field(description="Canonical positive numeric identifier wire shape.")
    pool_id: Annotated[int, Field(strict=True, ge=1)] = Field(description="Canonical positive numeric identifier wire shape.", alias="poolId")
    team_id_a: Annotated[int, Field(strict=True, ge=1)] = Field(description="Canonical positive numeric identifier wire shape.", alias="teamIdA")
    team_id_b: Annotated[int, Field(strict=True, ge=1)] = Field(description="Canonical positive numeric identifier wire shape.", alias="teamIdB")
    match_date: datetime = Field(description="RFC 3339 timestamp normalized to UTC on Blockout-owned wires.", alias="matchDate")
    season: Annotated[str, Field(strict=True, max_length=255)]
    set: Optional[StrictStr] = None
    score: Optional[StrictStr] = None
    status: MatchStatusEnum
    live_code: Optional[StrictInt] = Field(default=None, alias="liveCode")
    last_live_link_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Canonical positive numeric identifier wire shape.", alias="lastLiveLinkId")
    last_live_link_status: Optional[LiveLinkStatusEnum] = Field(default=None, alias="lastLiveLinkStatus")
    last_live_link_provider: Optional[LiveProviderEnum] = Field(default=None, alias="lastLiveLinkProvider")
    last_live_link_url: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, alias="lastLiveLinkUrl")
    last_live_link_owner_auth0_id: Optional[StrictStr] = Field(default=None, alias="lastLiveLinkOwnerAuth0Id")
    last_live_link_created_at: Optional[datetime] = Field(default=None, description="RFC 3339 timestamp normalized to UTC on Blockout-owned wires.", alias="lastLiveLinkCreatedAt")
    __properties: ClassVar[List[str]] = ["id", "poolId", "teamIdA", "teamIdB", "matchDate", "season", "set", "score", "status", "liveCode", "lastLiveLinkId", "lastLiveLinkStatus", "lastLiveLinkProvider", "lastLiveLinkUrl", "lastLiveLinkOwnerAuth0Id", "lastLiveLinkCreatedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatchLiveModerationSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if set (nullable) is None
        # and model_fields_set contains the field
        if self.set is None and "set" in self.model_fields_set:
            _dict['set'] = None

        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if live_code (nullable) is None
        # and model_fields_set contains the field
        if self.live_code is None and "live_code" in self.model_fields_set:
            _dict['liveCode'] = None

        # set to None if last_live_link_id (nullable) is None
        # and model_fields_set contains the field
        if self.last_live_link_id is None and "last_live_link_id" in self.model_fields_set:
            _dict['lastLiveLinkId'] = None

        # set to None if last_live_link_status (nullable) is None
        # and model_fields_set contains the field
        if self.last_live_link_status is None and "last_live_link_status" in self.model_fields_set:
            _dict['lastLiveLinkStatus'] = None

        # set to None if last_live_link_provider (nullable) is None
        # and model_fields_set contains the field
        if self.last_live_link_provider is None and "last_live_link_provider" in self.model_fields_set:
            _dict['lastLiveLinkProvider'] = None

        # set to None if last_live_link_url (nullable) is None
        # and model_fields_set contains the field
        if self.last_live_link_url is None and "last_live_link_url" in self.model_fields_set:
            _dict['lastLiveLinkUrl'] = None

        # set to None if last_live_link_owner_auth0_id (nullable) is None
        # and model_fields_set contains the field
        if self.last_live_link_owner_auth0_id is None and "last_live_link_owner_auth0_id" in self.model_fields_set:
            _dict['lastLiveLinkOwnerAuth0Id'] = None

        # set to None if last_live_link_created_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_live_link_created_at is None and "last_live_link_created_at" in self.model_fields_set:
            _dict['lastLiveLinkCreatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatchLiveModerationSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "poolId": obj.get("poolId"),
            "teamIdA": obj.get("teamIdA"),
            "teamIdB": obj.get("teamIdB"),
            "matchDate": obj.get("matchDate"),
            "season": obj.get("season"),
            "set": obj.get("set"),
            "score": obj.get("score"),
            "status": obj.get("status"),
            "liveCode": obj.get("liveCode"),
            "lastLiveLinkId": obj.get("lastLiveLinkId"),
            "lastLiveLinkStatus": obj.get("lastLiveLinkStatus"),
            "lastLiveLinkProvider": obj.get("lastLiveLinkProvider"),
            "lastLiveLinkUrl": obj.get("lastLiveLinkUrl"),
            "lastLiveLinkOwnerAuth0Id": obj.get("lastLiveLinkOwnerAuth0Id"),
            "lastLiveLinkCreatedAt": obj.get("lastLiveLinkCreatedAt")
        })
        return _obj
