global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - alerts.yml
scrape_configs:
  - job_name: core-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["core-service:9090"]
  - job_name: core-worker
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["core-worker:9090"]
