CREATE TABLE raw_division_mapping
(
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  division_id       BIGINT,
  league_code       VARCHAR(255) NOT NULL,
  raw_division_name VARCHAR(255) NOT NULL,
  season            VARCHAR(255) NOT NULL,
  format            VARCHAR(255) CHECK (format IN ('SIX', 'FOUR')),
  gender            VARCHAR(255) CHECK (gender IN ('M', 'F', 'O')),
  created_at        TIMESTAMP(6),
  last_update       TIMESTAMP(6),
  CONSTRAINT uix_raw_division_mapping UNIQUE (
                                              raw_division_name,
                                              league_code,
                                              season
    )
);
