CREATE TABLE scraper_status
(
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL UNIQUE CHECK (name IN ('SCRAPER', 'SCRAPER_CLUBS')),
  enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
  last_update TIMESTAMP(6)
);

INSERT INTO scraper_status (name, enabled, last_update)
SELECT 'SCRAPER', false, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1
                  FROM scraper_status
                  WHERE name = 'SCRAPER');

INSERT INTO scraper_status (name, enabled, last_update)
SELECT 'SCRAPER_CLUBS', false, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1
                  FROM scraper_status
                  WHERE name = 'SCRAPER_CLUBS');
