CREATE TABLE IF NOT EXISTS app_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maintenance BOOLEAN NOT NULL DEFAULT FALSE,
    message VARCHAR(1024),
    image_url VARCHAR(2048),
    min_version_ios VARCHAR(32),
    min_version_android VARCHAR(32),
    store_url_ios VARCHAR(2048),
    store_url_android VARCHAR(2048),
    force_update_message VARCHAR(1024),
    last_update TIMESTAMPTZ(6)
);

INSERT INTO app_status (
    maintenance,
    message,
    image_url,
    min_version_ios,
    min_version_android,
    store_url_ios,
    store_url_android,
    force_update_message,
    last_update
)
VALUES (
    FALSE,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NOW()
);