server:
  port: 8087

spring:
  application:
    name: ${APPLICATION_NAME:workersearch}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  config:
    import: optional:file:.env.local[.properties]
    on-missing-location: fail

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  elasticsearch:
    index:
      create-index: false

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

auth0:
  domain: ${AUTH0_DOMAIN}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}
  token-refresh-delay: 48h

api:
  club:
    url: ${CLUB_API_URL}
  team:
    url: ${TEAM_API_URL}
  pool:
    url: ${POOL_API_URL}
  config:
    url: ${CONFIG_API_URL}
