"""
    Blockout Competition Service Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field
from typing_extensions import Annotated
from blockout_contract_clients.competition_service.models.competition_association_internal_response import CompetitionAssociationInternalResponse
from blockout_contract_clients.competition_service.models.competition_statistics_snapshot_internal_request import CompetitionStatisticsSnapshotInternalRequest

from blockout_contract_clients.competition_service.api_client import ApiClient, RequestSerialized
from blockout_contract_clients.competition_service.api_response import ApiResponse
from blockout_contract_clients.competition_service.rest import RESTResponseType


class CompetitionStatisticsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def replace_competition_statistics(
        self,
        pool_id: Annotated[int, Field(strict=True, ge=1)],
        team_id: Annotated[int, Field(strict=True, ge=1)],
        competition_statistics_snapshot_internal_request: CompetitionStatisticsSnapshotInternalRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CompetitionAssociationInternalResponse:
        """Replace association statistics

        Atomically replaces all seventeen statistics for the identified association. Partial snapshots and null statistics are invalid.

        :param pool_id: (required)
        :type pool_id: int
        :param team_id: (required)
        :type team_id: int
        :param competition_statistics_snapshot_internal_request: (required)
        :type competition_statistics_snapshot_internal_request: CompetitionStatisticsSnapshotInternalRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._replace_competition_statistics_serialize(
            pool_id=pool_id,
            team_id=team_id,
            competition_statistics_snapshot_internal_request=competition_statistics_snapshot_internal_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CompetitionAssociationInternalResponse",
            '400': "ProblemDetail",
            '401': "ProblemDetail",
            '403': "ProblemDetail",
            '404': "ProblemDetail",
            '500': "ProblemDetail",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def replace_competition_statistics_with_http_info(
        self,
        pool_id: Annotated[int, Field(strict=True, ge=1)],
        team_id: Annotated[int, Field(strict=True, ge=1)],
        competition_statistics_snapshot_internal_request: CompetitionStatisticsSnapshotInternalRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CompetitionAssociationInternalResponse]:
        """Replace association statistics

        Atomically replaces all seventeen statistics for the identified association. Partial snapshots and null statistics are invalid.

        :param pool_id: (required)
        :type pool_id: int
        :param team_id: (required)
        :type team_id: int
        :param competition_statistics_snapshot_internal_request: (required)
        :type competition_statistics_snapshot_internal_request: CompetitionStatisticsSnapshotInternalRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._replace_competition_statistics_serialize(
            pool_id=pool_id,
            team_id=team_id,
            competition_statistics_snapshot_internal_request=competition_statistics_snapshot_internal_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CompetitionAssociationInternalResponse",
            '400': "ProblemDetail",
            '401': "ProblemDetail",
            '403': "ProblemDetail",
            '404': "ProblemDetail",
            '500': "ProblemDetail",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def replace_competition_statistics_without_preload_content(
        self,
        pool_id: Annotated[int, Field(strict=True, ge=1)],
        team_id: Annotated[int, Field(strict=True, ge=1)],
        competition_statistics_snapshot_internal_request: CompetitionStatisticsSnapshotInternalRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Replace association statistics

        Atomically replaces all seventeen statistics for the identified association. Partial snapshots and null statistics are invalid.

        :param pool_id: (required)
        :type pool_id: int
        :param team_id: (required)
        :type team_id: int
        :param competition_statistics_snapshot_internal_request: (required)
        :type competition_statistics_snapshot_internal_request: CompetitionStatisticsSnapshotInternalRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._replace_competition_statistics_serialize(
            pool_id=pool_id,
            team_id=team_id,
            competition_statistics_snapshot_internal_request=competition_statistics_snapshot_internal_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CompetitionAssociationInternalResponse",
            '400': "ProblemDetail",
            '401': "ProblemDetail",
            '403': "ProblemDetail",
            '404': "ProblemDetail",
            '500': "ProblemDetail",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _replace_competition_statistics_serialize(
        self,
        pool_id,
        team_id,
        competition_statistics_snapshot_internal_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if pool_id is not None:
            _path_params['poolId'] = pool_id
        if team_id is not None:
            _path_params['teamId'] = team_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if competition_statistics_snapshot_internal_request is not None:
            _body_params = competition_statistics_snapshot_internal_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json',
                    'application/problem+json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/api/v2/competitions/pools/{poolId}/teams/{teamId}/stats',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )
