CREATE TABLE user_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    entity_id BIGINT NOT NULL,
    entity_type VARCHAR(255) NOT NULL CHECK (entity_type IN ('TEAM', 'POOL')),
    created_at TIMESTAMP(6),
    CONSTRAINT fk_user_fav_user FOREIGN KEY (user_id) REFERENCES users (id)
);