# coding: utf-8

"""
    Blockout Clubs Service Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateClubInternalRequest(BaseModel):
    """
    Club creation data carried by the canonical multipart JSON part. An optional image part creates the logo. Address is intentionally absent because the current create path drops it; adding it requires a separately approved behavior correction.
    """ # noqa: E501
    id: Annotated[str, Field(strict=True, max_length=255)]
    raw_name: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="rawName")
    name: Annotated[str, Field(strict=True, max_length=255)]
    city: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    postal_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="postalCode")
    email: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    phone_number: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="phoneNumber")
    website: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    __properties: ClassVar[List[str]] = ["id", "rawName", "name", "city", "postalCode", "email", "phoneNumber", "website"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateClubInternalRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict['postalCode'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if phone_number (nullable) is None
        # and model_fields_set contains the field
        if self.phone_number is None and "phone_number" in self.model_fields_set:
            _dict['phoneNumber'] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict['website'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateClubInternalRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "rawName": obj.get("rawName"),
            "name": obj.get("name"),
            "city": obj.get("city"),
            "postalCode": obj.get("postalCode"),
            "email": obj.get("email"),
            "phoneNumber": obj.get("phoneNumber"),
            "website": obj.get("website")
        })
        return _obj
