package com.blockout.config.division.persistence;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

class DivisionFlywayMigrationTest {

    @Test
    void migrationAddsANonNullRevisionDefaultedToZero() throws Exception {
        String url = "jdbc:h2:mem:mrg439;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "");
                var statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE division (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        main_color VARCHAR(255) NOT NULL,
                        first_gradient_color VARCHAR(255) NOT NULL,
                        second_gradient_color VARCHAR(255) NOT NULL,
                        third_gradient_color VARCHAR(255) NOT NULL
                    )
                    """);
        }
        Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("6")
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "");
                var statement = connection.createStatement()) {
            statement.executeUpdate("""
                    INSERT INTO division (
                        name, main_color, first_gradient_color, second_gradient_color, third_gradient_color
                    ) VALUES ('Elite', '#1', '#2', '#3', '#4')
                    """);
            try (var result = statement.executeQuery("SELECT revision FROM division WHERE name = 'Elite'")) {
                assertThat(result.next()).isTrue();
                assertThat(result.getLong("revision")).isZero();
                assertThat(result.wasNull()).isFalse();
            }
        }
    }
}
