export enum EnumDivisionCode {
    MSL = "MSL",
    SP6 = "SP6",
    LBM = "LBM",
    ELITE = "ELITE",
    ELITEAVENIR = "ELITEAVENIR",
    N2 = "N2",
    N3 = "N3",
    PRENAT = "PRENAT",
    REG = "REG",
    M21 = "M21",
    M18 = "M18",
    M15 = "M15",
    M13 = "M13",
    M11 = "M11",
    OTHER = "OTHER",
};

export const DivisionCodeLabels: Record<EnumDivisionCode, string> = {
    [EnumDivisionCode.MSL]: "Marmara SpikeLigue",
    [EnumDivisionCode.SP6]: "Saforelle Power 6",
    [EnumDivisionCode.LBM]: "Ligue B Masculine",
    [EnumDivisionCode.ELITE]: "Élite",
    [EnumDivisionCode.ELITEAVENIR]: "Élite Avenir",
    [EnumDivisionCode.N2]: "Nationale 2",
    [EnumDivisionCode.N3]: "Nationale 3",
    [EnumDivisionCode.PRENAT]: "Prénationale",
    [EnumDivisionCode.REG]: "Régionale",
    [EnumDivisionCode.M21]: "M21",
    [EnumDivisionCode.M18]: "M18",
    [EnumDivisionCode.M15]: "M15",
    [EnumDivisionCode.M13]: "M13",
    [EnumDivisionCode.M11]: "M11",
    [EnumDivisionCode.OTHER]: "Division inconnue",
};