# coding: utf-8

"""
    Blockout Competition Service Internal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompetitionAssociationInternalResponse(BaseModel):
    """
    Competition-owned association and full statistics snapshot without persistence identity or audit timestamps.
    """ # noqa: E501
    pool_id: Annotated[int, Field(strict=True, ge=1)] = Field(alias="poolId")
    team_id: Annotated[int, Field(strict=True, ge=1)] = Field(alias="teamId")
    club_id: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="clubId")
    active: StrictBool
    points: StrictInt
    played: StrictInt
    wins: StrictInt
    losses: StrictInt
    wins_three_to_zero: StrictInt = Field(alias="winsThreeToZero")
    wins_three_to_one: StrictInt = Field(alias="winsThreeToOne")
    wins_three_to_two: StrictInt = Field(alias="winsThreeToTwo")
    losses_zero_to_three: StrictInt = Field(alias="lossesZeroToThree")
    losses_one_to_three: StrictInt = Field(alias="lossesOneToThree")
    losses_two_to_three: StrictInt = Field(alias="lossesTwoToThree")
    won_sets: StrictInt = Field(alias="wonSets")
    lost_sets: StrictInt = Field(alias="lostSets")
    won_points: StrictInt = Field(alias="wonPoints")
    lost_points: StrictInt = Field(alias="lostPoints")
    points_penalty: StrictInt = Field(alias="pointsPenalty")
    coef_sets: Union[StrictFloat, StrictInt] = Field(alias="coefSets")
    coef_points: Union[StrictFloat, StrictInt] = Field(alias="coefPoints")
    __properties: ClassVar[List[str]] = ["poolId", "teamId", "clubId", "active", "points", "played", "wins", "losses", "winsThreeToZero", "winsThreeToOne", "winsThreeToTwo", "lossesZeroToThree", "lossesOneToThree", "lossesTwoToThree", "wonSets", "lostSets", "wonPoints", "lostPoints", "pointsPenalty", "coefSets", "coefPoints"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompetitionAssociationInternalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompetitionAssociationInternalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "poolId": obj.get("poolId"),
            "teamId": obj.get("teamId"),
            "clubId": obj.get("clubId"),
            "active": obj.get("active"),
            "points": obj.get("points"),
            "played": obj.get("played"),
            "wins": obj.get("wins"),
            "losses": obj.get("losses"),
            "winsThreeToZero": obj.get("winsThreeToZero"),
            "winsThreeToOne": obj.get("winsThreeToOne"),
            "winsThreeToTwo": obj.get("winsThreeToTwo"),
            "lossesZeroToThree": obj.get("lossesZeroToThree"),
            "lossesOneToThree": obj.get("lossesOneToThree"),
            "lossesTwoToThree": obj.get("lossesTwoToThree"),
            "wonSets": obj.get("wonSets"),
            "lostSets": obj.get("lostSets"),
            "wonPoints": obj.get("wonPoints"),
            "lostPoints": obj.get("lostPoints"),
            "pointsPenalty": obj.get("pointsPenalty"),
            "coefSets": obj.get("coefSets"),
            "coefPoints": obj.get("coefPoints")
        })
        return _obj
