export const CONFIG = {
    AUTH0_DOMAIN: process.env.EXPO_PUBLIC_AUTH0_DOMAIN || '',
    AUTH0_CLIENT_ID: process.env.EXPO_PUBLIC_AUTH0_CLIENT_ID || '',
    API_MATCHES_BASE_URL: process.env.EXPO_PUBLIC_API_MATCHES_BASE_URL || '',
    API_POOLS_BASE_URL: process.env.EXPO_PUBLIC_API_POOLS_BASE_URL || '',
    API_TEAMS_BASE_URL: process.env.EXPO_PUBLIC_API_TEAMS_BASE_URL || '',
    API_COMPETITIONS_BASE_URL: process.env.EXPO_PUBLIC_API_COMPETITIONS_BASE_URL || '',
    API_USERS_BASE_URL: process.env.EXPO_PUBLIC_API_USERS_BASE_URL || '',
    API_SEARCH_BASE_URL: process.env.EXPO_PUBLIC_API_SEARCH_BASE_URL || '',
    API_GATEWAY_BASE_URL: process.env.EXPO_PUBLIC_API_GATEWAY_BASE_URL || '',
    API_CONFIG_BASE_URL: process.env.EXPO_PUBLIC_API_CONFIG_BASE_URL || '',
    API_CLUBS_BASE_URL: process.env.EXPO_PUBLIC_API_CLUBS_BASE_URL || '',
    API_REPORTS_BASE_URL: process.env.EXPO_PUBLIC_API_REPORTS_BASE_URL || '',
    API_NOTIFICATIONS_BASE_URL: process.env.EXPO_PUBLIC_API_NOTIFICATIONS_BASE_URL || '',
    MAP_URL: process.env.EXPO_PUBLIC_MAP_URL || '',
    INSTAGRAM_URL: process.env.EXPO_PUBLIC_INSTAGRAM_URL || '',
    ENTITLEMENT_BLOCKOUT_PRO: process.env.EXPO_PUBLIC_ENTITLEMENT_BLOCKOUT_PRO || '',
    REVENUECAT_IOS_API_KEY: process.env.EXPO_PUBLIC_REVENUECAT_IOS_API_KEY || '',
    REVENUECAT_ANDROID_API_KEY: process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY || '',
};

export const AUTH0_CONFIG = {
    domain: CONFIG.AUTH0_DOMAIN,
    clientId: CONFIG.AUTH0_CLIENT_ID,
};